### ISSUE TITLE
pre-v2.0.0 - changelog

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#138]
I will prepare a complete changelog for a new version v1.10.0 here:

- [FIX] - update MyBB and GitHub URL links (http:// -> https://)
- [FIX] - lot of typos in language files
- [FIX] - jGowl popup notifications use default MyBB theme CSS
- [FIX] - duplications of posts/threads in thanks/likes search
- [FIX] - extra space in member profile statistics + fix lang variables
- [FIX] - wrong path for ACP lang file
- [FIX] - remove promotion task on uninstall
- [ENHANCEMENT] - add missing lang variables for ACP settings
- [ENHANCEMENT] - rebuild (recount) is located in the MyBB default ACP page
- [ENHANCEMENT] - rename CSS and templates to follow MyBB standards
- [ENHANCEMENT] - clean up code and remove unnecessary files
- [ENHANCEMENT] - links executing JS functions return false and point to javascript.void(0) instead of hashtags
- [NEW FEATURE] - add ability to thank/like own posts + settings to remove own thanks/likes from search list
- [NEW FEATURE] - maximum thanks/likes in a time period - configurable for every usergroup + popup notification with remaining thanks/like and alerts
- [NEW FEATURE] - MyBB usergroup promotion system - new parameter for thanks/likes given
- ...

Thank you very much @SvePu for your contribution! Great work!

**Update from older versions without any data lost:**
1) Deactivate
2) Uninstall (DO NOT drop tables from DB!)
3) Copy and rewrite old files
4) Install & activate again
5) Check plugin settings
6) You are done!

**CSS code for non-styled jGowl popus**
```CSS
.jGrowl .jGrowl-notification.jgrowl_success,
.jGrowl .jGrowl-notification.jgrowl_error{
    background: black !important;
    border: 1px solid black !important;
    color: #fff !important;
}
```

Maybe we should mark this as v2.0.0 - really huge changelog and many changes.
